---
- hosts: all
  tasks:
    - shell: uname -r
      register: uname_eval 
    - shell: echo $HOME
      register: home_eval
    - set_fact: linux_kernel={{ uname_eval.stdout }} home_folder={{ home_eval.stdout }}
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes
    - name: install essential packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - build-essential
        - git
        - tree
        - vim
        - rsync
        - wget
        - curl
        - python-pycurl
        - autoconf
        - libncurses5-dev
        - cmake
        - python-dev
        - nodejs
        - tmux
    - command: git clone https://github.com/fish-shell/fish-shell creates="{{ home_folder }}/fish-shell"
    - command: autoconf chdir="fish-shell"
    - shell: ./configure chdir="fish-shell"
    - command: make chdir="fish-shell"
    - shell: sudo make install chdir="fish-shell"
    - command: curl -O https://raw.github.com/gkostyanikov/dotfiles/master/.vimrc creates="{{ home_folder }}/.vimrc"
    - command: curl -O https://raw.github.com/gkostyanikov/dotfiles/master/.tmux.conf creates="{{ home_folder }}/.tmux.conf"
    - command: mkdir -p .config/fish
    - command: curl -O https://raw.github.com/gkostyanikov/dotfiles/master/config.fish chdir=".config/fish" creates="{{ home_folder }}/.config/fish/config.fish"
    - command: curl -O https://raw.github.com/gkostyanikov/dotfiles/master/.gemrc chdir=".config/fish" creates="{{ home_folder }}/.gemrc"
    - command: git clone https://github.com/gmarik/vundle.git {{ home_folder}}/.vim/bundle/vundle creates="{{ home_folder }}/.vim/bundle/vundle"
    - command: vim +BundleInstall +qall
    - shell: ./install.sh chdir=".vim/bundle/YouCompleteMe"
    - command: git clone https://github.com/sstephenson/rbenv.git {{ home_folder }}/.rbenv creates="{{ home_folder }}/.rbenv"
    - command: git clone https://github.com/sstephenson/ruby-build.git {{ home_folder}}/.rbenv/plugins/ruby-build creates="{{ home_folder }}/.rbenv/plugins/ruby-build"

    - name: install aufs
      apt: pkg=linux-image-extra-{{ linux_kernel }}
      sudo: yes
    - name: add postgresql-9.3 repo 
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present update_cache=yes
      sudo: yes
    - name: add postgresql-9.3 key 
      apt_key: url='http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc' state=present
      sudo: yes
    - name: update apt cache
      apt: update_cache=yes
      sudo: yes
    - name: install postgresql-9.3 packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - postgresql-9.3
        - libpq-dev
    - name: add docker key 
      apt_key: url='https://get.docker.io/gpg' state=present
      sudo: yes
    - name: add docker repo 
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present update_cache=yes
      sudo: yes
    - name: install docker
      apt: pkg=lxc-docker state=present
      sudo: yes
